export const ADD_NEW_VALUE = "ADD_NEW_VALUE";
export const CLEAR_VALUES = "CLEAR_VALUES";
export const EXPERESSION = "EXPERESSION";
export const EVALUATE_EXPRESSION = "EVALUATE_EXPRESSION";
export const PERFORM_OPERATION = "PERFORM_OPERATION";